creation_rules:
  - path_regex: secrets/testnet\.env
    age: age1gpe6clrwzvfjlkwm2ww4a00f0ktk49raaslgs2zr3r0vzkcez9fsd97vzs
  # Kubernetes Secret manifests for testnet LKE cluster
  - path_regex: clusters/testnet/.*\.secret\.yaml
    age: age1gpe6clrwzvfjlkwm2ww4a00f0ktk49raaslgs2zr3r0vzkcez9fsd97vzs
