apiVersion: v1
kind: Secret
metadata:
    name: exchange-postgres
    namespace: exchange
type: Opaque
stringData:
    PGUSER: ENC[AES256_GCM,data:CEgDOHKqpDw=,iv:8ubM2DcCxCZ89xoVvcdnZWkP1RgO+peouolfz3ei2Ps=,tag:mzF06BEPh3auIR4+fg6RFA==,type:str]
    PGPASSWORD: ENC[AES256_GCM,data:L+UWUOdnRsm0lGeMX5tsdOC/BG9Nlo/8,iv:CWqdtmfTM7KPT02Pmh03Zthcu9DiTLN/yfYNh6JT9JI=,tag:M4e20Dir7jT2Uahedr33Hw==,type:str]
    PGHOST: ENC[AES256_GCM,data:HmNC4xQFOs0kjBbF5ekPM9Zo5Q3f3HXoGpaXaVqYtneB6iTyrbxT7QNX6vDsWBQLYn1pXg==,iv:SSL9v/k8vKXGt7SklPuPv4brRL5Unw+3QPDSGEOqMvY=,tag:L+FdkGuOGlXkdGeaipeFbQ==,type:str]
    PGPORT: ENC[AES256_GCM,data:KmgdhHo=,iv:wYe9B+m7kxjDQDKO+qRbgfaS2KCGbAD3Wwr36dLu7ek=,tag:Jgk/G4nte4NRahkCCF8jng==,type:str]
    PGDATABASE: ENC[AES256_GCM,data:v5nOlb8GNg==,iv:veGJJI9zPpUOUyWi/8mFa4uYIEojiJnAea2ossgfi3A=,tag:UFK8RRQs+sQmkCyeMQE8jg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHck9KTkFaUnFMaXlCeGdH
            V3kySGVLRDlLa3lndGVpaXA5LzFBWlVuMmxFCitGZkFraTZZbWpqZnl0TURLa1Zj
            azV3SENITkdWM2xNWjhKUHF1c1FRSkUKLS0tIG5Ed0J3S3JGMHBOSjZiZUw2dFVY
            UU9UOU9Bc3BhN3lkRjRQbEJJVDZmV0EKTEdFAfxaUQ1Uf6w6o0VuqoYCDHtu+K/7
            CX9hyNeYq2SdaD1Z9q7vIjc+E+7BwN+LFxxbm62RIrmJMc+0qtJung==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gpe6clrwzvfjlkwm2ww4a00f0ktk49raaslgs2zr3r0vzkcez9fsd97vzs
    encrypted_regex: ^(stringData|data)$
    lastmodified: "2026-08-14T01:39:28Z"
    mac: ENC[AES256_GCM,data:Rc1dY61J+RqjF2YmMUlpD/Eq5S1itPB/sZWmqS0pHzFcrA8oT2yhJuPufd29sgBC58TNYJM1CQOLaf/EwHdECrgScZ7RyEbbqHHJQ4AQVIeLBr1ikHkdOsSd4InMByxdRkb1gxHL0KvkkkOuy3X8D2TmG9VjWJT+nWYn9XbetVc=,iv:8ZWfzRAXnOJclunwmVfJirGwlzyzARLR3+vlCES6bMI=,tag:LSzxqRRT/Mmn4Bj4ibTWjA==,type:str]
    version: 3.13.1
