apiVersion: ENC[AES256_GCM,data:IY8=,iv:rQ4uv19Cqwt+AWQuD+OVpMvn/zC0EGDtJXdjFmdntuI=,tag:WwZLdB3Nkh8IMkCSxQVFzw==,type:str]
kind: ENC[AES256_GCM,data:uCBQw/zD,iv:gUKQCDf7yivDDxCSPdopPTDCcNkrLbeDqu/n7sfgGtQ=,tag:a9GmHGjTcJH/wPtkO0PwTA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Zz3D2VmVs6CCDmXE,iv:yBpoHvRIU068we/ettNW9NcM4JUpnpBuBDyfftAP6w0=,tag:XBwl4doGoE4Z3FqRQjwq1w==,type:str]
    namespace: ENC[AES256_GCM,data:XhXX,iv:zkhO1BpLog18+xTi9RXom5VbPnHjFWrmzpaZVDgWnGo=,tag:3DanfLN1q7RskMY5D9KHSw==,type:str]
type: ENC[AES256_GCM,data:p0+kieUE,iv:R/Tq3MmJa0imj+dew82K/+AwmE8wN9lR7g8YnO1RtTo=,tag:XtlBwJia7bVtsxHmy260yA==,type:str]
stringData:
    seed: ENC[AES256_GCM,data:bcS+QNuUybdoTPunN0yp/FsBTWYM45FDxOI+HJUxsHtSAgHnoXcjXUK99IN50XkNeY0DpLdXbA9z95EtXmcvrr8ZqeZq13+gFEwjQgxKR4kBYOXrIlDulEWHMINU+ZQD3G+ny70P6jzSqxG79TGvDPY6VFBCmNPbVEG/PsUrqw==,iv:+rUi40w3u+9rMr2xARA0eCLqoMwRSmKt/+o/y+uVkzQ=,tag:E+u8B0pzv3nUCo9Xf5i9xw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmakZZbkFkQW85OWpGUDVB
            am5KSVc4YTU2aXJlemNRb3pEY2o1QncxZFNrCjQ2b09vVE9oNjZOYWRhVmMxZ0Y2
            dG1DZXdmYkxJcGZJaXo4d2hzTkZIbE0KLS0tIHJneFJSeW5jR2J6UFpNRzc1TFhs
            NkZQVXJ6UmRQMmZBN0dsUWdFUXUwZ28KqJgC47ftzko1qyX58/5jKRSKQlqzsE0c
            tiZE7Pg0V8hX/MqMUmgEzwfvetlwRDc/7ekoHPtrhQyCUv8b5lHfFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gpe6clrwzvfjlkwm2ww4a00f0ktk49raaslgs2zr3r0vzkcez9fsd97vzs
    lastmodified: "2026-06-22T17:32:47Z"
    mac: ENC[AES256_GCM,data:4SQMRdA9cn/qWujGWuxpb469e3LL3EoaVuO9NM67PvXrTq/S36dlShzp7CifsSMWzxNewYhKOuiLgL5NZK+RwFAMDKsZaRPRCiEomQB4IgeW54WyOiEOw+c2IGss7kP7JUz5VftQuZGo9hJLnCvuzBhv09BBB3ZbRDII8AWi8rg=,iv:p/03XRCC/3Fhr8YQeXartUlSH2r3c1se0yW22fiDwq4=,tag:V+6ApvmM/SehbhjZl/tqmA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
