apiVersion: ENC[AES256_GCM,data:RyU=,iv:X8TRDq8yI6iw4aEDLhwJr5Os1Xb5ZqKob0uhGrVRoGA=,tag:x9i7dKh6HNreLmWFEOzsfA==,type:str]
kind: ENC[AES256_GCM,data:0lazgK3W,iv:xID0ad3npISeXmhOMxt8aOFprXUkv2QmKPD209QqgDc=,tag:pkRNvRHbD3T/5Pej7JN/SQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KGxef0orjTOhR7BGXHJ8,iv:McLJlUf14XlFrciU/bebjVYszI9xH/ro6XXUsQlJPsI=,tag:T7E7bWmjVUzTfdhWPr0XWg==,type:str]
    namespace: ENC[AES256_GCM,data:CyS1,iv:zbnN5weU81DyFZqR+Uc3VWwcLozWEd0y5qLMGA8PISU=,tag:SDYWs3W6ysGm8SskfaSjkw==,type:str]
type: ENC[AES256_GCM,data:QZFFXtWF,iv:5o2RqqUXqg/+XVk1cBKCQsBcwmeDKwOiwxQV0RIzeso=,tag:2ZYTqItPjWHQsxuPMi+jEA==,type:str]
stringData:
    seed: ENC[AES256_GCM,data:YwHVpVL5C2IqiGjRb4Y/JB4fA2PB4Mp83AVenPiXaFD2K4O47mZLWOpVZgJpR1tHfLdApQfL51oZyIEmHKEPVHq4ZhgvIyPfELJRzixuQ05AqU8Fat7LowYtcwl5T16gvMZgz4Y7roOkwJ4GDnI3nSyopMMCoVwDg6pa,iv:ZelNGs79iiz4l4MA4rKMp7Vh8bmd+yl4vKTdQ3ZMOnE=,tag:FnAQrC6ikgyC0/CUyOXq8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1am9tOEgyRzY2K3A2MW5W
            c0FLV1dRT0pob1hERjM2bm53clBsZnJEZEhrCnlESlVBT0tvUi9EN0FTcEhONkFE
            cFdwYjZjY29vYjVnUDlSc0xCazdhL3MKLS0tIEsvYVRVcGRLTWlKNUN2Y2Z0VEl5
            cWhwWGF3TERsTTViMEM0MGF4VnZQcmsKyHoqibIhJ7EkNwQAYqNhh3wQ4+Fa7yLu
            hWuq7oWHk210tqdVNit3nQ2Z2w42/jx/4M8E9gZvbBheH/KNx0HrvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gpe6clrwzvfjlkwm2ww4a00f0ktk49raaslgs2zr3r0vzkcez9fsd97vzs
    lastmodified: "2026-06-10T20:48:50Z"
    mac: ENC[AES256_GCM,data:6bxUDnHjHwmOEsa4rXDTg4jLTBm8EAVQoHlIqn/7B+Sr1sQbNvaQEhRjl7zipxjeBIPv7gipCWRtGOeF+RO7UsIAdyFLDxdIViA7mUjlUO3xoOzGpDXeDlU2QxWpBaApD6q8cWRKHFkqVI0qmfygkFweQCx4WThtOwnIcy1BxUk=,iv:iunkxwOMD9HS2shOPs+JHB+7eiVIssZyBAJLFm2sLVk=,tag:mgRwf3iTX6BbkEtJ6tJtng==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
