apiVersion: ENC[AES256_GCM,data:HJc=,iv:OLQ9UAVmCh3JtWLMyhJ7gFrVb6uhEPMZVF7vK5ivBg4=,tag:7YyQPWGVYmQMdd7s00eaWg==,type:str]
kind: ENC[AES256_GCM,data:OQU27qEb,iv:QRn1wFXDaXBn1iCCin1JCHpByqsutweiau0AIRk03fg=,tag:ppYAM/yT7Xs5rlB9ae6SiA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lpYSe4d6VGdapvqN/x7l,iv:x7WfTkq14dwdDqLAFKmMQF8z5izpGjRmSmmFwcXfTuU=,tag:NkY61dv75GqOrHbAz3wDnA==,type:str]
    namespace: ENC[AES256_GCM,data:i2CH,iv:gl0BfOUwjGfe+i7FPM5SDCMgdajvr4it1ViLZTiV2to=,tag:6ElyNkeLlcjSEKqkFRZtdg==,type:str]
type: ENC[AES256_GCM,data:tzaLJYiH,iv:0TZINhm2wicqFZ6D/U2RrvdfhYoKJVqyTRnNFWFJLkI=,tag:+ck+0FLL8p5vRbJpsRJ3DQ==,type:str]
stringData:
    seed: ENC[AES256_GCM,data:vHGxc+Vzkhh8yd/GG9b5TngfyKMErkz4NGgzUeT2lAuH6SUj55mmHRtv4Pkq7Jz9ZOEb0nfm+CcbpL5ppBy98f1cWuxJDDFCQ4Q9JzcygESo1m3pnRhRjCdS,iv:kZ6m0N/1iO73SvDV8WU25XpK12XPP157eA4C9bf6b38=,tag:D1GmXsTo9Y5/tl6tWD6Ezg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeVVXKy9mRUxsUFVYTDMv
            M1NGaC9EYks4OGpjNjZqMC8wZW9kNFRiU2k0Ck5uRDVOSWZrWWdrNG9jejZHRHQw
            dEJ4SmRCQnpkTGhoWFRSeWl4c2RGdncKLS0tIDVybXYralJlcVErSkUvR2RDYkZS
            TU96TmNDTEhLdCtUdW1YVkkzZlMyN3MKPI2kpX0k+x6IkYLwAE0vM+WNnCrH+zQP
            A3SAZb+luldXdCTQrudyDYVEk2OWccoiIVwPTL02Tz+7huKXiBwBkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gpe6clrwzvfjlkwm2ww4a00f0ktk49raaslgs2zr3r0vzkcez9fsd97vzs
    lastmodified: "2026-06-10T17:29:40Z"
    mac: ENC[AES256_GCM,data:gR1aYxPMN4Vz3eNO/XvqBi8XsxO0I6bwXTG8liXKIvXTUOMtKixiFOFj5ZY+itNuD9u0e4KsGULEPQnQZryb/0eWDboVvsvyIaWQ2KjzXR9AeaOBzNsLd+FhecIC9M6MXyJRpr3phstLYda0mpYpgeoDV+M+eQYrMG6WY7oO6Bc=,iv:1PEymEJL6MY1xyY5fP9ht+uMinRE+A1EjwCbpreZNI4=,tag:R6w0jPeTLUQDwA0hUYDvPw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
