apiVersion: ENC[AES256_GCM,data:Sos=,iv:agtteASH/zZulXRntjDdlYRzzd9aNnez/1paQ2e0+4w=,tag:rk+46sU4VCIndgbB/P90Yg==,type:str]
kind: ENC[AES256_GCM,data:HRdmz+Sc,iv:QqXCJ1dNT0CfWlJEhLWI9/hZ9qC6ocLLJStTMxb8XVQ=,tag:pb0u+wT03T7Lx43oAe58Sg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:EaFFJNeMlKI+jCu74PPZ,iv:yxHk4GE0RzKAftpTpAZ1+I1Ekhakrpw1rhHUKTFORro=,tag:74y6Dm1vc+Q5zJMUWKHzkA==,type:str]
    namespace: ENC[AES256_GCM,data:ZPuG,iv:7NXedNGmUOCcSAmiAdR9E0M4CWUgqNFj3UIiyb0sKZo=,tag:jT9DVgHtdywtsXaPr7ztbA==,type:str]
type: ENC[AES256_GCM,data:Y6dGDD7N,iv:CQqEgw3dWrEuAghh72u4wVpZwfP1E3jadnxnmj4b3rI=,tag:tsRt2tyWH5KrjgiEozKQkg==,type:str]
stringData:
    seed: ENC[AES256_GCM,data:oP1giYvA2gwZtMZFQfataegSY2BbMZWrg9n8VlWmuckMgwJshwdKe3usj421n7WkS8jp+z0fvTc093noHUsAorXPv9kXk6vL9fcSSemtbYkQu6s51RFmsSmxveOx,iv:iEGb9q0ff0207syrdkfjnBk4jn+OPqrEg3lxlQuavno=,tag:Pbh9BULs8QSJABQOH07dgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVzIvWFpMakNDdHlKWXo3
            QlFOSWczQnhsOWJrS2FxZGlQbG9hb0hFVnpvCnc1NW5DcTVOb2NvRWFSUjhtVkdI
            VEVpbnhFQlNxK3ZwVEwvYjhHZDc4MUkKLS0tIG4yLzJzSWFUTVRPaGExdXdTL3BC
            QmZZMTZqalE2bmU2cnp6bC9mL3Q1U1kK6znlIsQTkMtxZ/0aMLyaxZEWlMz5bSFT
            vExknwWf6DgenqIzYgD538AY5fhDHMCydvIcjoFQy9W9mXNyCbCVOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gpe6clrwzvfjlkwm2ww4a00f0ktk49raaslgs2zr3r0vzkcez9fsd97vzs
    lastmodified: "2026-06-10T17:29:40Z"
    mac: ENC[AES256_GCM,data:kdbVFmK28nhGJnLQeUebhP5n2dcqx9Fvk6X+IQcbbgU4C2DxhaC/7q5rzw/H8AkdSAZV8Ac4/LFHS9FIvL5hqHTe/OWhbCwud14rFKJvFNRoXIYffg09vYqBTbwm071l21/2bzs9/PlK55Di29QAiMeOQTSY8smWxtqkV4n7QgM=,iv:dWDx3kGXS4F86+DA5KA4f63Tipw0pjxNA/0CqqWV1+0=,tag:YeXN9+lb6l1upM/14/h1Ng==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
