apiVersion: ENC[AES256_GCM,data:qHk=,iv:ZW2QGUjVFOCfzj56Y5uDETxpus0gOnsSThElfGVqMYI=,tag:Ee9KmajPqun6sbU4ZLOIkA==,type:str]
kind: ENC[AES256_GCM,data:+awXVsXu,iv:KKYJejh7svN8B959bXlsSb+3cy+eJ3MZMatTkXnZBuA=,tag:nOS+5xyEOdKfVf+FxXB4AQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jR+Q/v/LbNhOzyPl,iv:ZZ7KigLkLXREbvuhep1npl1oFbMzAEwFMt6swpxNUDQ=,tag:PKWRwl2O5ZStkctqtGhDxQ==,type:str]
    namespace: ENC[AES256_GCM,data:lU77,iv:QEilAdIfbU6EibKzJJetgR5pvOba5gni4X53q07izaI=,tag:soZ5It9kUk+DcM3+Q19tGw==,type:str]
type: ENC[AES256_GCM,data:f12D8H8c,iv:4wnCSgUK4DAuF3fnqmmLLlHq64id2Le/pQRHF0f7oGQ=,tag:/T16K8DxwV3V17l01kjtLg==,type:str]
stringData:
    seed: ENC[AES256_GCM,data:OzMuQF0BcD9y/8C0eGZIp5NYlxbdfCqD7oIYzgztyOCaLUoijEZH54cxGAA+EuJfM/Wxnc5PMD4J+3yjmffj4yUNc9RlIuauwPtaxumQZwFYq404DqBx0KhR4O40LTRXCwujUKKpJDZWZV1xe8C3V+1ibij6+3g3UGc+L393VKRZ,iv:I0cEDTqMPKVjbPFscnLI6h3xNRPogZ0A4MgalRCQgFA=,tag:57CaJ0sqNYaz5rkBbhHqBQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWGc5ZEJWUmJGT2ZUTzJX
            enp5dDhFaUxYZWFRUHFPWlNWWUZzQ25UK1ZNCnVMY205TzR2YTNYd2FLUnEzS2ZO
            VnM0Uk1oRDhVUGN1UzJPTXByc3pQY1kKLS0tIEdJREVIWExUM3llN1N4TFZMaUNl
            RHFva3R1OGg4QlRkcFdKdFVYUFJaME0KNmJVAQ9zwCL8LtLyWLteq7+8FgwLbogW
            VlcgZ/4PyMa3icgJm8vBAJ1s+Fsddxo8FbQxJVpH8hv5dEtNkJb66Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gpe6clrwzvfjlkwm2ww4a00f0ktk49raaslgs2zr3r0vzkcez9fsd97vzs
    lastmodified: "2026-06-22T17:32:47Z"
    mac: ENC[AES256_GCM,data:j6v/moq9QdhN+2/Nyf0ZAXBEO5tHP8ppYyNUElIrG9jcyQgGiqn8/cSbrDlOhi8Jk9j+iY7XxZC3O2hYnpUaa2Mm+5QVBnKYVwc9mMJ9VAu0ogi8FgxkKbAF0Pt0wFcY8O/n7B2uLikM1goC/LoNl7UAHZ1K8mBisoKsGqeNJLc=,iv:xS/Dbrryyzi6ZBpSmN9XfeVqNy+ZlDTGmE8dVPodtRU=,tag:jzsUms96CcyjOn/Fbtjd2A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
