name: LKE Available Versions
on:
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Query available LKE k8s versions
        env:
          LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
        run: |
          curl -s -H "Authorization: Bearer $LINODE_TOKEN" \
            https://api.linode.com/v4/lke/versions | jq -r '.data[].id' | sort
